### ISSUE TITLE
HELP please

### ISSUE THREAD

**Issue by LeFajitas** [SergioPrinci/rococo#3]
Add me on Discord i have many questions for you about the Karuta bot in python please =)
MiMoZz #4686

**Comment by SergioPrinci** [comment]
Done, but please use this as the place of the main questions, so that everyone can read and understand the problem.

**Comment by SergioPrinci** [comment]
Discussion continued on Discord, homever the issue was found and the patch is now online 02826a64b825d16faae682e9c649e66908fce6bd
